spring.application.name=bootbatch
spring.datasource.url=jdbc:mysql://localhost:3306/bootwork
spring.datasource.username=root
spring.datasource.password=thanish@1234


#batch related configurations written here
spring.batch.jdbc.initialize-schema=always
spring.sql.init.mode=always